#!/bin/sh
#	add-on for qryparse that reports regex and html special chars in input
#	code by Jack
#		input: expets output from qryparse as arg
#		does: if badchars exits 1, else exits 0
#		error: if more than one arg exits 2
#

#proper args?
if test ! $# = 1
then
	exit 2
fi

# contains chars	 ][<>^$*   or    ='-   (ie value is option flag)
echo "$1" | grep -q -e '[<>]' -e '='\''-'

# echo "$1" | grep -q -e '[]<>[^$*]' -e '='\''-'
if test $? = 0
then
	exit 1
else
	exit 0
fi


