#!/bin/sh
#
#	regex_safe
#	code by Jack
#		purpose: adds escapes to special chars prior to regex use
#		input: a stream
#		outputs: a stream with escapes added

# turns . into \. which reads as just . literal (tested in sed, not grep)
sed s/'\.'/'\''\.'/g	|
# turns ^ into \^ which reads as ^ literal (tested in sed and grep)
sed s/'\^'/'\\^'/g	|
# turns $ into \$ which reads as $ literal (tested in sed and grep)
sed s/'\$'/'\\$'/g	|
# turns * into \* which reads as * literal (tested in sed and grep)
sed s/*/'\\*'/g		|
# turns [ into \[ which reads as [ literal (tested in sed and grep)
sed s/'\['/'\\['/g


#still to cover ] and \(...\)?
